"""Research lifecycle contracts for downstream project authors."""

from noetrium_platform.research.experimentation.api import (
    CompiledResearchPlan,
    ExperimentRunner,
    ExperimentRunnerPort,
    ResearchBindingContribution,
    ResearchMethodHost,
    ResearchMethodHostPort,
    ResearchPlanDiff,
    ResearchStudyDefinition,
    compile_research_plan,
    diff_research_plans,
    resolve_research_requirements,
)
from noetrium_platform.research.experimentation.run.api import (
    RunArtifactKind,
    RunArtifactSnapshotReceipt,
)
from noetrium_platform.research.experimentation.study.api import (
    BenchmarkTaskSet,
    TaskDefinition,
    BoundStudyUnitExecutionPort,
    BoundStudyVariantExecutionPort,
    ExperimentPlan,
    StudyAssignment,
    StudyConcurrencyPolicy,
    StudyExecutionUnit,
    StudyMatrixExecutionReport,
    StudyMetricAggregate,
    StudyMetricObservation,
    StudyProtocol,
    StudyVariantExecutionPort,
    StudyVariantSpec,
    VariantBinding,
    VariantKind,
    MeasurementRecord,
    MeasurementValue,
    MeasurementValueKind,
    TrialMatrixExecutionReport,
)
from noetrium_platform.research.experimentation.study.runtime import (
    BasicStudyMetricAggregator,
    DeterministicStudyAssignment,
    StudyMatrixExecutor,
)
from noetrium_platform.research.experimentation.workbench.api import (
    AggregationFunction, AggregationSpec, BaselineRegistryPort, BaselineSpec,
    DataColumn, DataTable, EvaluationContext, EvaluationStage, FigureCategory,
    FigureCell, FigureKind, FigureOutputFormat, FigurePoint, FigureSeries,
    FigureSpec, FigureStyle, GroupComparison, InferenceResult, MetricSummary,
    MissingValuePolicy, MultipleComparisonMethod, MultipleComparisonResult,
    PairedComparison, RenderedResearchPackage, ResearchEvaluation, ResearchReport,
    SplitStrategy, MeasurementRecordTableAdapter, StudyObservationTableAdapter,
)
from noetrium_platform.research.experimentation.workbench.providers import (
    CsvTableReader, JsonlTableReader, PdfFigureRenderer,
    PublicationFigureRenderer, StandardTableRenderer, SvgFigureRenderer,
)
from noetrium_platform.research.experimentation.workbench.runtime import (
    InMemoryBaselineRegistry, ResearchFigureFactory, ResearchLifecycle,
    ScientificStatistics, TablePipeline,
)
from noetrium_platform.research.experimentation.run.control.api import (
    RunControlAction,
    RunControlActionFailure,
    RunControlConflict,
    RunControlError,
    RunControlEventReceipt,
    RunControlIntegrityError,
    RunControlNotFound,
    RunControlPhase,
    RunControlPort,
    RunControlReceipt,
    RunControlReceiptReference,
    RunControlRecordKind,
    RunControlRequest,
    RunControlStaleGeneration,
    RunControlTarget,
    RunControlTransitionOutcome,
    RunEvidenceValidity,
    RunExecutionOutcome,
    RunOutcomeProjection,
    RunScientificValidity,
    RunTaskOutcome,
)
from noetrium_platform.research.experimentation.run.manifest.api.evidence import (
    DerivedEvidenceArtifact,
    EvidenceBundleManifest,
    EvidenceBundleReceipt,
    EvidenceBundleStatus,
    EvidenceStreamDescriptor,
)

__all__ = [
    "CompiledResearchPlan", "ExperimentRunner", "ExperimentRunnerPort",
    "ResearchBindingContribution", "ResearchMethodHost", "ResearchMethodHostPort",
    "ResearchPlanDiff", "ResearchStudyDefinition", "compile_research_plan",
    "diff_research_plans", "resolve_research_requirements",
    "RunArtifactKind", "RunArtifactSnapshotReceipt", "RunControlAction",
    "RunControlActionFailure", "RunControlConflict", "RunControlError",
    "RunControlEventReceipt", "RunControlIntegrityError", "RunControlNotFound",
    "RunControlPhase", "RunControlPort", "RunControlReceipt",
    "RunControlReceiptReference", "RunControlRecordKind", "RunControlRequest",
    "RunControlStaleGeneration", "RunControlTarget", "RunControlTransitionOutcome",
    "RunEvidenceValidity", "RunExecutionOutcome", "RunOutcomeProjection",
    "RunScientificValidity", "RunTaskOutcome", "DerivedEvidenceArtifact",
    "EvidenceBundleManifest", "EvidenceBundleReceipt", "EvidenceBundleStatus",
    "EvidenceStreamDescriptor",
    "BenchmarkTaskSet", "TaskDefinition",
    "BoundStudyUnitExecutionPort", "BoundStudyVariantExecutionPort", "ExperimentPlan",
    "StudyAssignment", "StudyConcurrencyPolicy", "StudyExecutionUnit",
    "StudyMatrixExecutionReport", "StudyMetricAggregate", "StudyMetricObservation",
    "StudyProtocol", "StudyVariantExecutionPort", "StudyVariantSpec", "VariantBinding",
    "VariantKind", "MeasurementRecord", "MeasurementValue", "MeasurementValueKind",
    "TrialMatrixExecutionReport", "BasicStudyMetricAggregator", "DeterministicStudyAssignment",
    "StudyMatrixExecutor",
    "AggregationFunction", "AggregationSpec", "BaselineRegistryPort", "BaselineSpec", "CsvTableReader", "DataColumn", "DataTable", "EvaluationContext", "EvaluationStage", "FigureCategory", "FigureCell", "FigureKind", "FigureOutputFormat", "FigurePoint",
    "FigureSeries", "FigureSpec", "FigureStyle", "GroupComparison", "InferenceResult", "JsonlTableReader",
    "MetricSummary", "MultipleComparisonMethod", "MultipleComparisonResult", "MeasurementRecordTableAdapter", "MissingValuePolicy",
    "PairedComparison", "RenderedResearchPackage", "ResearchEvaluation", "ResearchFigureFactory",
    "ResearchLifecycle", "ResearchReport", "StudyObservationTableAdapter",
    "ScientificStatistics", "SplitStrategy", "StandardTableRenderer", "PdfFigureRenderer", "PublicationFigureRenderer", "SvgFigureRenderer",
    "TablePipeline",
]
